# Generated by Django 4.2.3 on 2023-07-31 15:33
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('theme', models.CharField(max_length=400, verbose_name='Тема статьи')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст статьи')),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='',
                                          verbose_name='Картинка для статьи')),
                ('dateOfPublish', models.DateField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
