# Generated by Django 4.2.3 on 2023-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forChildren',
            field=models.BooleanField(default=False, verbose_name='Для детей'),
        ),
        migrations.AddField(
            model_name='item',
            name='forMales',
            field=models.BooleanField(default=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(default='', max_length=500, verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание товара'),
        ),
    ]
