# Generated by Django 4.2.3 on 2023-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка для статьи'),
        ),
    ]
