# Generated by Django 4.2.3 on 2023-07-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
