# Generated by Django 4.2.3 on 2023-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_forfemales_alter_item_formales_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя бренда')),
                ('siteLink', models.CharField(max_length=250, verbose_name='Ссылка на сайт')),
                ('pic', models.ImageField(upload_to='', verbose_name='Картинка бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
