# Generated by Django 4.2.3 on 2023-07-27 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favoriteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок статьи')),
                ('theme', models.CharField(max_length=30, verbose_name='Тема статьи')),
                ('text', models.CharField(max_length=500, verbose_name='Текст статьи')),
                ('dateOfPublishment', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Vacansy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок вакансии')),
                ('post', models.CharField(max_length=30, verbose_name='Должность вакансии')),
                ('description', models.CharField(max_length=300, verbose_name='Описание должности')),
                ('skills', models.CharField(max_length=300, verbose_name='Навыки')),
                ('salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Примерная З.П.')),
                ('dateOfPublishment', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
