# Generated by Django 4.2.3 on 2023-07-27 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Одежда', max_length=20, verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='mark',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка товара'),
        ),
    ]
