# Generated by Django 4.2.3 on 2023-07-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_category_item_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата отзыва'),
        ),
    ]
