# Generated by Django 4.2.3 on 2023-07-30 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Причина вовзрата')),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Отклонен', 'Отклонен'), ('Подтвержден', 'Подтвержден')], default='В обработке', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
